# Generated by Django 4.0 on 2021-12-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_alter_tblsignup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsignup',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
